#!/usr/bin/env bash
# Transfers a file from our client to a server using 4 parameters
# Before running this script: we list server's existing content
# ssh ubuntu@100.26.224.43 -i ~/.ssh/id_rsa 'ls ~/'
#touch newfile.html
#run this again to check new content is transferred to server
#ssh ubuntu@100.26.224.43 -i ~/.ssh/id_rsa 'ls ~/'
if [$# -lt 3]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi