#!/usr/bin/env bash
#install ngix on web server , on port 80
#Query Nginx at its root (/) with a GET request (requesting html page)
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart