#!/usr/bin/env bash
#install ngix on web server , on port 80
#Query Nginx at its root (/) with a GET request (requesting html page)
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
