#!/bin/env bash

#install Nginx
sudo apt update
sudo apt install -y nginx

#configure Nginx to add custom response header
sudo sed -i '/http {/a \    server {\n        add_header X-Served-By $hostname;\n    }' /etc/nginx/nginx.conf

#restart Nginx
sudo service nginx restart
