#!/usr/bin/env bash
#removing the defualt config of nginx
#making symbolic link to make nginx use port 80
rm etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart