#!/usr/bin/env bash
# script to  make nginx listen to port 80 (default)
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
