#!/usr/bin/env bash
#print best school 10 times using while
#in 9th time print Hi

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
      echo "Hi"
    fi
    ((i++))
done
